### ISSUE TITLE
1R-MYBs count confuse

### ISSUE THREAD

**Issue by cfz1998** [bpucker/MYB_annotator#2]
When i used MYB_annotator to detect MYBs in Arabidopsis_thaliana.
I got a few number of 1R-MYBs. Does it normal?

Number of 1R-MYBs: 2
Number of R2R3-MYBs: 121
Number of 3R-MYBs: 5
Number of pseudo MYBs and unclassified ones: 5

The running code is:
```python
python /data/chaofan/software/MYB_annotator-main/MYB_annotator.py  --baits /data/chaofan/software/MYB_annotator-main/MYB_baits.fasta --info /data/chaofan/software/MYB_annotator-main/MYB_baits.txt --out Arabidopsis_thaliana --subject Arabidopsis_thaliana.pep --refmybs /data/chaofan/software/MYB_annotator-main/AthRefMYBs.txt --raxml /data/chaofan/miniconda/bin/raxmlHPC --cpu 20
```

**Comment by bpucker** [comment]
This looks good to me. The MYB_annotator is focused on finding R2R3-MYBs. 1R-MYBs and MYB-like sequences are not part of this R2R3/3R-MYB clade and considered as outgroup unless they are derived from R2R3/3R-MYBs and lost one repeat recently. Slight differences in the results can be due to different versions of the Arabidopsis thaliana annotation. Also, you could find differences if you would analyze an accession that is not Col-0. Does this answer your question?

**Comment by cfz1998** [comment]
> i

Yes. Thank you!

**Comment by cfz1998** [comment]
> This looks good to me. The MYB_annotator is focused on finding R2R3-MYBs. 1R-MYBs and MYB-like sequences are not part of this R2R3/3R-MYB clade and considered as outgroup unless they are derived from R2R3/3R-MYBs and lost one repeat recently. Slight differences in the results can be due to different versions of the Arabidopsis thaliana annotation. Also, you could find differences if you would analyze an accession that is not Col-0. Does this answer your question?

Yes. Thank you!
